import vehicles
car = vehicles.Car('Ford', 'Cyan')
print(car)
print()
car.start_engine()
car.drive(15)
car.add_fuel(100)
car.repair(only_full_repair=False)
car.play_music()
print()
print()

sportcar = vehicles.Sportcar('Porsche', 'Red')
print(sportcar)
print()
sportcar.start_engine()
sportcar.drive(5)
sportcar.upgrade()
sportcar.pit_stop()
sportcar.drive(10)
sportcar.play_music()
sportcar.stop_engine()
print()
print()

boat = vehicles.Boat('Ann-Marie', 'White')
print(boat)
print()
boat.set_sail()
boat.sail(50)
boat.make_sound()
print()
print()

steamboat = vehicles.SteamBoat('Supreme', 'Black')
print(steamboat)
print()
steamboat.set_sail()
steamboat.sail(15)
print()
steamboat.start_engine()
steamboat.drive(50)
steamboat.add_fuel(200)
steamboat.play_music()